Provider: Yaml

GameSettings:
  AllowCreative : "lobby"

Sound:
  Volume: 0.9

Database:
  Host: "127.0.0.1"
  Port: "5432"
  Database: "mcbe"
  User: "kuro"
  Pass: "********"

Web:
  DataPath: "/var/www/html/mcbe/data/"
  SkinDays: 7
  SkinMake: ""

Twitter:
  ConsumerKey: ""
  ConsumerSecret: ""
  AccessToken: ""
  AccessTokenSecret: ""
  BroadcastID: 0

Command:
  Disable: "version,plugins,seed,defaultgamemode,me,difficulty,op,deop,whitelist,save-on,save-off,save-all,give,effect,enchant,particle,gamerule,title,reload,xp,status,gc,timings,debugpaste"

NameCommand:
  AllowDays: 3

SqlStatement:
  Sql0001: "SELECT upd_date FROM player_display WHERE xuid = ?"
  Sql0002: "INSERT INTO player_display (xuid, name, tag, com, add_date, upd_date) VALUES (?, ?, null, null, current_timestamp, current_timestamp) ON CONFLICT (xuid) DO UPDATE SET name=?, upd_date = current_timestamp"
  Sql0003: "SELECT * FROM (SELECT xname as name FROM player UNION SELECT name FROM player_display ) TGT WHERE TGT.name = ?"
  Sql0004: "INSERT INTO player VALUES(?,?,?,?,?,?,?,?,?,?,?,current_timestamp,current_timestamp, 0, ?)"
  Sql0005: "UPDATE player SET host=?, ip=?, cid=?, uuid=?, device_id=?, device_model=?, device_os=?, game_version=?, upd_date=current_timestamp, play_status=? WHERE xuid=?"
  Sql0006: "UPDATE player SET play_status='ﾛｸﾞｲﾝ' WHERE xuid=?"
  Sql0007: "UPDATE player SET play_time=play_time+?, play_status='' WHERE xuid=?"
  Sql0008: "UPDATE player SET play_status='' WHERE xuid=?"
  Sql0009: "SELECT name FROM player_display WHERE xuid = ?"
  Sql0010: "SELECT * FROM version ORDER BY add_date DESC limit 5 offset 0"
  Sql0011: "SELECT xuid FROM (SELECT xuid, xname as name FROM player UNION SELECT xuid, name FROM player_display ) TGT WHERE LOWER(TGT.name) = ?"
  Sql0012: "UPDATE player_info SET break=break+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0013: "UPDATE player_info SET place=place+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0014: "UPDATE player_info SET kick=kick+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0015: "UPDATE player_info SET kill=kill+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0016: "UPDATE player_info SET death=death+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0017: "UPDATE player_info SET chat=chat+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0018: "INSERT INTO player_info VALUES(?,?,?,?,?,?,?,?,current_timestamp,current_timestamp)"
  Sql0019: "SELECT xuid FROM player_info WHERE xuid=?"
  Sql0020: "UPDATE player_info SET login=login+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0021: "SELECT D.name, P.xname FROM (SELECT xuid, xname FROM player) P INNER JOIN (SELECT xuid, name FROM player_display) D ON P.xuid = D.XUID WHERE LOWER(D.name) = ?"
  Sql0022: "INSERT INTO item (id, meta, name, price, add_date, updater, upd_date) VALUES (?, 0, ?, 0, current_timestamp, '', current_timestamp)"
  Sql0023: "SELECT id,name,price FROM item ORDER BY id"
  Sql0024: "UPDATE item SET price=?, updater=?, upd_date=current_timestamp WHERE id=? AND meta=0"
  Sql0025: "SELECT 名前, 元名, 権限 FROM v_player ORDER BY LOWER(名前)"
  Sql0026: "SELECT 元名 FROM v_player WHERE 名前=?"
  Sql0027: "UPDATE player SET rank=? WHERE xname=?"
  Sql0028: "SELECT rank FROM player WHERE xuid=?"

ConfigVersion: 1