Provider: Yaml

# ゲーム設定
GameSettings:
  # 初期値
  FirstSpawn : "lobby"
  # 住民初期値
  SecondSpawn : "city"
  # アイテムマーク
  ItemTag : "-123"
  # ボリューム
  Volume: 0.9

# データベース設定
Database:
  Host: "127.0.0.1"
  Port: "5432"
  Database: "mcbe"
  User: "kuro"
  Pass: "********"

# WEB設定
Web:
  DataPath: "/var/www/html/mcbe/data/"
  WebPath: "http://kuro.host/mcbe/data/"
  SkinDays: 7
  SkinMake: ""

# TWITTER設定
Twitter:
  ConsumerKey: ""
  ConsumerSecret: ""
  AccessToken: ""
  AccessTokenSecret: ""
  BroadcastID: 0

# DISCORD設定
Discord:
  # ボットトークン
  botToken: ""
  # チャットチャネルID
  channelId: ""
  # 違反報告チャンネルID
  ban_channelId: ""
  # ボットの再生中のステータスを設定
  botStatus: "MCBE<123鯖>"

# Nukkitコマンド
Command:
  # 無効にするコマンド
  Disable: "list,version,plugins,seed,defaultgamemode,me,difficulty,op,deop,whitelist,save-on,save-off,save-all,give,effect,enchant,particle,gamerule,title,reload,xp,status,gc,timings,debugpaste"

# nameコマンド
NameCommand:
  # 再設定までの日数
  AllowDays: 1

# NPCワード
Npc:
  Type01: "テストだぜ"
  Type02: "テストだよ"

ConfigVersion: 1