Provider: Yaml

# ゲーム設定
GameSettings:
  # 初期値
  FirstSpawn : "lobby"
  # 住民初期値
  SecondSpawn : "city"
  # アイテムマーク
  ItemTag : "-123"
  # ボリューム
  Volume: 0.9

# データベース設定
Database:
  Host: "127.0.0.1"
  Port: "5432"
  Database: "mcbe"
  User: "kuro"
  Pass: "********"

# WEB設定
Web:
  DataPath: "/var/www/html/mcbe/data/"
  WebPath: "http://kuro.host/mcbe/data/"
  SkinDays: 7
  SkinMake: ""

# TWITTER設定
Twitter:
  ConsumerKey: ""
  ConsumerSecret: ""
  AccessToken: ""
  AccessTokenSecret: ""
  BroadcastID: 0

# DISCORD設定
Discord:
  # ボットトークン
  botToken: ""
  # チャットチャネルID
  channelId: ""
  # 違反報告チャンネルID
  ban_channelId: ""
  # ボットの再生中のステータスを設定
  botStatus: "MCBE<123鯖>"

# Nukkitコマンド
Command:
  # 無効にするコマンド
  Disable: "list,version,plugins,seed,defaultgamemode,me,difficulty,op,deop,whitelist,save-on,save-off,save-all,give,effect,enchant,particle,gamerule,title,reload,xp,status,gc,timings,debugpaste"

# nameコマンド
NameCommand:
  # 再設定までの日数
  AllowDays: 1

# NPCワード
Npc:
  Type01: "テストだぜ"
  Type02: "テストだよ"

# SQLステートメント
SqlStatement:
  Sql0001: "SELECT upd_date FROM player_display WHERE xuid = ?"
  Sql0002: "INSERT INTO player_display (xuid, name, tag, com, add_date, upd_date) VALUES (?, ?, null, null, current_timestamp, current_timestamp) ON CONFLICT (xuid) DO UPDATE SET name=?, upd_date = current_timestamp"
  Sql0003: "SELECT * FROM (SELECT xname as name FROM player UNION SELECT name FROM player_display ) TGT WHERE TGT.name = ?"
  Sql0004: "INSERT INTO player VALUES(?,?,?,?,?,?,?,?,?,?,?,current_timestamp,current_timestamp, 0, ?)"
  Sql0005: "UPDATE player SET host=?, ip=?, cid=?, uuid=?, device_id=?, device_model=?, device_os=?, game_version=?, upd_date=current_timestamp, play_status=? WHERE xuid=?"
  Sql0006: "UPDATE player SET play_status='ﾛｸﾞｲﾝ' WHERE xuid=?"
  Sql0007: "UPDATE player SET play_time=play_time+?, play_status='' WHERE xuid=?"
  Sql0008: "UPDATE player SET play_status='' WHERE xuid=?"
  Sql0009: "SELECT name, tag, upd_date FROM player_display WHERE xuid = ?"
  Sql0010: "SELECT * FROM version ORDER BY add_date DESC limit 5 offset 0"
  Sql0011: "SELECT xuid FROM (SELECT xuid, xname as name FROM player UNION SELECT xuid, name FROM player_display ) TGT WHERE LOWER(TGT.name) = ?"
  Sql0012: "UPDATE player_info SET break=break+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0013: "UPDATE player_info SET place=place+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0014: "UPDATE player_info SET kick=kick+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0015: "UPDATE player_info SET kill=kill+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0016: "UPDATE player_info SET death=death+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0017: "UPDATE player_info SET chat=chat+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0018: "INSERT INTO player_info VALUES(?,?,?,?,?,?,?,?,current_timestamp,current_timestamp)"
  Sql0019: "SELECT xuid FROM player_info WHERE xuid=?"
  Sql0020: "UPDATE player_info SET login=login+1, upd_date=current_timestamp WHERE xuid=?"
  Sql0021: "SELECT D.name, P.xname FROM (SELECT xuid, xname FROM player) P INNER JOIN (SELECT xuid, name FROM player_display) D ON P.xuid = D.XUID WHERE LOWER(D.name) = ?"
  Sql0022: "INSERT INTO item (id, meta, name, price, add_date, updater, upd_date) VALUES (?, 0, ?, 0, current_timestamp, '', current_timestamp) ON CONFLICT (id,meta) DO UPDATE SET name=?, upd_date = current_timestamp"
  Sql0023: "SELECT id,name,price,CASE COALESCE(ban,0) WHEN 0 THEN '' ELSE '〇' END AS ban FROM item ORDER BY id"
  Sql0024: "UPDATE item SET price=?, updater=?, upd_date=current_timestamp WHERE id=? AND meta=0"
  Sql0025: "SELECT 名前, 元名, 権限 FROM v_player ORDER BY LOWER(名前)"
  Sql0026: "SELECT 元名 FROM v_player WHERE 名前=?"
  Sql0027: "UPDATE player SET rank=? WHERE xname=?"
  Sql0028: "SELECT rank FROM player WHERE xuid=?"
  Sql0029: "INSERT INTO player_wallet (xuid, money, add_date, upd_date) VALUES (?, ?, current_timestamp, current_timestamp) ON CONFLICT (xuid) DO UPDATE SET money=player_wallet.money+EXCLUDED.money, upd_date = current_timestamp"
  Sql0030: "INSERT INTO log_cmd (log_date, xuid, rank, cmd, arg01, arg02, arg03, arg04, arg05, arg06, message) VALUES (current_timestamp,?,?,?,?,?,?,?,?,?,?)"
  Sql0031: "INSERT INTO log_window (log_date, xuid, rank, win, res01, res02, res03, res04, res05, res06, message) VALUES (current_timestamp,?,?,?,?,?,?,?,?,?,?)"
  Sql0032: "INSERT INTO log_error (log_date, xuid, rank, place, error, message) VALUES (current_timestamp,?,?,?,?,?)"
  Sql0033: "INSERT INTO log_block (log_date, xuid, rank, gamemode, level, x, y, z, act, block_id, block_meta, block_name, custom_name) VALUES (current_timestamp,?,?,?,?,?,?,?,?,?,?,?,?)"
  Sql0034: "SELECT tag FROM player_display WHERE tag=?"
  Sql0035: "INSERT INTO player_display (xuid, name, tag, com, add_date, upd_date) VALUES (?, null, ?, null, current_timestamp, current_timestamp) ON CONFLICT (xuid) DO UPDATE SET tag=?"
  Sql0036: "SELECT BL.log_date, COALESCE(NICK.name, USR.name) AS name, BL.act, BL.block_name, BL.block_id, BL.block_meta FROM (SELECT xuid, act, block_name, block_id, block_meta, log_date FROM log_block WHERE level=? AND x=? AND y=? AND z=?) BL INNER JOIN (SELECT xuid, xname as name FROM player) USR ON BL.xuid=USR.xuid LEFT OUTER JOIN (SELECT xuid, name FROM player_display) NICK ON BL.xuid=NICK.xuid ORDER BY log_date DESC"
  Sql0037: "SELECT PL.*, PD.name FROM (SELECT xuid, xname, host, ip, cid, device_id, device_model, device_os FROM player) PL LEFT JOIN (SELECT xuid, name FROM player_display) PD ON PL.xuid=PD.xuid WHERE LOWER(PL.xname) LIKE ? OR LOWER(PD.name) LIKE ?"
  Sql0038: "SELECT UR.xname, UD.name FROM (SELECT xuid, xname, host, ip, cid, device_id FROM player WHERE LENGTH(cid) >= 6 AND ip=?) UR LEFT JOIN (SELECT xuid, name FROM player_display) UD ON UR.xuid = UD.xuid ORDER BY xname, name"
  Sql0039: "SELECT UR.xname, UD.name FROM (SELECT xuid, xname, host, ip, cid, device_id FROM player WHERE LENGTH(cid) >= 6 AND host=?) UR LEFT JOIN (SELECT xuid, name FROM player_display) UD ON UR.xuid = UD.xuid ORDER BY xname, name"
  Sql0040: "SELECT UR.xname, UD.name FROM (SELECT xuid, xname, host, ip, cid, device_id FROM player WHERE LENGTH(cid) >= 6 AND cid=?) UR LEFT JOIN (SELECT xuid, name FROM player_display) UD ON UR.xuid = UD.xuid ORDER BY xname, name"
  Sql0041: "SELECT UR.xname, UD.name FROM (SELECT xuid, xname, host, ip, cid, device_id FROM player WHERE LENGTH(cid) >= 6 AND device_id=?) UR LEFT JOIN (SELECT xuid, name FROM player_display) UD ON UR.xuid = UD.xuid ORDER BY xname, name"
  Sql0042: "SELECT name FROM (SELECT xname as name FROM player UNION SELECT name FROM player_display ) TGT WHERE LOWER(TGT.name) LIKE ? ORDER BY name"
  Sql0043: "SELECT play_time FROM player WHERE xuid=?"
  Sql0044: "UPDATE player SET status=null"
  Sql0045: "UPDATE item SET ban=?, updater=?, upd_date=current_timestamp WHERE id=? AND meta=0"
  Sql0046: "SELECT xuid, xname, name, tag, play_time, money, login, break, place, kick, death, kill, chat FROM v_player_info WHERE xuid=?"
  Sql0047: "SELECT * FROM world WHERE name=?"
  Sql0048: "INSERT INTO world (name, master, manager01, manager02, manager03, zone, viewdistance, splitchat, hunger_speed, survival, creative, spectator, adventure, fly, break, place, pvp, tagitem, crafting, bed, effect, enchant, mob, boss, updater, upd_date) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,current_timestamp) ON CONFLICT (name) DO UPDATE SET name=?, master=?, manager01=?, manager02=?, manager03=?, zone=?, viewdistance=?, splitchat=?, hunger_speed=?, survival=?, creative=?, spectator=?, adventure=?, fly=?, break=?, place=?, pvp=?, tagitem=?, crafting=?, bed=?, effect=?, enchant=?, mob=?, boss=?, updater=?, upd_date=current_timestamp"
  Sql0049: "SELECT * FROM v_player_info WHERE xuid=?"
  Sql0050: "SELECT * FROM player_wallet WHERE xuid=?"
  Sql0051: "UPDATE player_wallet SET money=money-? WHERE xuid=?"
  Sql0052: "UPDATE player_wallet SET money=money+? WHERE xuid=?"
  Sql0053: "SELECT xname FROM v_player_info WHERE LOWER(xname)=? OR LOWER(name)=?"
  Sql0054: "INSERT INTO zone(level, x1, z1, x2, z2, gm, name, owner, message, public, sound, partner01, partner02, partner03, updater, upd_date) VALUES (?, ?, ?, ?, ?, ?, null, null, null, false, null, null, null, null, ?, current_timestamp)"
  Sql0055: "SELECT * FROM zone"

ConfigVersion: 1