name: OneTwoThreeBase
version: ${project.version}
api: ["1.0.8"]
author: kuro
description: OneTwoThreeBase
main: host.kuro.onetwothree.BasePlugin

permissions:
  onetwothree.warp:
    default: true
  onetwothree.warp.others:
    default: op

  onetwothree.name:
    default: true
  onetwothree.name.others:
    default: op

  onetwothree.xbox:
    default: true
  onetwothree.xbox.others:
    default: op

  onetwothree.touch:
    default: true
  onetwothree.touch.others:
    default: op

  onetwothree.price:
    default: op
  onetwothree.price.others:
    default: op

  onetwothree.rank:
    default: op
  onetwothree.rank.others:
    default: op

  onetwothree.sell:
    default: true
  onetwothree.sell.others:
    default: op