name: OneTwoThreeBase
version: ${project.version}
api: ["1.0.8"]
author: kuro
description: OneTwoThreeBase
main: host.kuro.onetwothree.BasePlugin

permissions:
  onetwothree.warp:
    default: true
  onetwothree.name:
    default: true
  onetwothree.xbox:
    default: true
  onetwothree.touch:
    default: op
  onetwothree.price:
    default: op
  onetwothree.rank:
    default: op
  onetwothree.sell:
    default: op
  onetwothree.reboot:
    default: op
  onetwothree.call:
    default: op
  onetwothree.list:
    default: true
  onetwothree.tag:
    default: true
  onetwothree.alias:
    default: op
  onetwothree.imadonkurai:
    default: true
  onetwothree.kv:
    default: op
  onetwothree.lag:
    default: op
  onetwothree.banitem:
    default: op
  onetwothree.rand:
    default: true
  onetwothree.kc:
    default: op
  onetwothree.npc:
    default: op
  onetwothree.info:
    default: true
  onetwothree.world:
    default: op
  onetwothree.ri:
     default: true
  onetwothree.pay:
    default: true